# Generated by Django 4.0.4 on 2023-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.CharField(default='', max_length=50)),
                ('color', models.CharField(default='', max_length=10)),
                ('eyecolor', models.CharField(default='', max_length=10)),
                ('DOB', models.DateField()),
                ('sex', models.CharField(default='', max_length=8)),
                ('weight', models.IntegerField()),
                ('medical_condition', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='adopt/images')),
            ],
        ),
    ]
