# Generated by Django 4.0.4 on 2023-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0003_animal_animaltype_animal_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='available_for_adoption',
            field=models.BooleanField(default=True),
        ),
    ]
