# Generated by Django 4.0.4 on 2023-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0004_animal_available_for_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animaltype', models.CharField(default='', max_length=50)),
                ('breeds', models.CharField(default='', max_length=50)),
                ('color', models.CharField(default='', max_length=10)),
                ('desc', models.TextField(default='', max_length=100)),
                ('DOB', models.DateField()),
                ('sex', models.CharField(default='', max_length=8)),
                ('weight', models.IntegerField()),
                ('medical_condition', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
