# Generated by Django 4.0.4 on 2023-07-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0005_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Surrender',
        ),
    ]
