# Generated by Django 4.0.4 on 2023-08-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0006_rename_image_surrender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='surrender',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
