# Generated by Django 4.0.4 on 2023-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0009_strayanimalrescue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strayanimalrescue',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
