# Generated by Django 4.0.4 on 2023-08-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petsansar', '0011_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='medical_condition',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='petsansar.animal'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
