# Generated by Django 4.0.4 on 2023-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
