# Generated by Django 4.0.4 on 2023-08-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0017_listadoptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('Accepted', 'Accepted'), ('Not Available', 'Not Available')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='listadoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('Accepted', 'Accepted'), ('Not Available', 'Not Available')], default='pending', max_length=20),
        ),
    ]
