# Generated by Django 4.0.4 on 2023-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsansar', '0018_alter_adoptionrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surrender',
            name='medical_certificate',
            field=models.ImageField(blank='True', null='True', upload_to='img/%y'),
            preserve_default='True',
        ),
    ]
